dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    packages:
      - graphviz
      - libgraphviz-dev
install:
  - pip install tox-travis codecov
script:
  - tox

after_success:
  - codecov
