dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - graphviz
install:
  - pip install tox-travis codecov
script:
  - tox

after_success:
  - codecov
