dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install tox-travis codecov
# command to run tests
script:
  - tox

after_success:
  - codecov
