dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "sudo apt install graphviz"
install:
  - pip install tox-travis codecov
script:
  - tox

after_success:
  - codecov
